services:
  - type: web
    name: utopia-proxy
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: rust/Dockerfile.render
    envVars:
      - key: PROXY_PROTOCOL
        value: http
      - key: HTTP_BACKEND_ENDPOINT
        value: host.docker.internal:5678
      - key: TCP_BACKEND_ENDPOINT
        value: 127.0.0.1:15432
