services:
  - type: web
    name: utopia-proxy
    runtime: docker
    plan: free
    dockerfile: ./Dockerfile
    dockerCommand: php -S 0.0.0.0:${PORT} -t public
    envVars:
      - key: PHP_VERSION
        value: "8.4"
      - key: PORT
        value: "3000"
