services:
  - type: web
    name: utopia-proxy
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: rust/Dockerfile
    envVars:
      - key: TCP_BACKEND_ENDPOINT
        value: localhost:5432
      - key: HTTP_BACKEND_ENDPOINT
        value: localhost:8080
